services:
  frontend:
    image: pl3lee/webjson-frontend:${SHA}
    container_name: webjson-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'

  web-api:
    image: pl3lee/webjson-web-api:${SHA}
    container_name: webjson-web-api
    restart: unless-stopped

    ports:
      - '3001:3001'
    env_file:
      - .env.api

  public-api:
    image: pl3lee/webjson-public-api:${SHA}
    container_name: webjson-public-api
    restart: unless-stopped

    ports:
      - '3002:3002'
    env_file:
      - .env.api

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webjson
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    
    
