services:
  frontend:
    image: pl3lee/webjson-frontend:${SHA}
    container_name: webjson-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'

  frontend-api:
    image: pl3lee/webjson-frontend-api:${SHA}
    container_name: webjson-frontend-api
    restart: unless-stopped

    ports:
      - '3001:3001'
    env_file:
      - .env.frontend.api

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webjson
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    
    
