services:
  frontend:
    image: pl3lee/restjson-frontend:${SHA}
    container_name: restjson-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'

  api:
    image: pl3lee/restjson-api:${SHA}
    container_name: restjson-api
    restart: unless-stopped

    ports:
      - '3001:3001'
    env_file:
      - .env.api
    volumes:
      - $HOME/.aws:/root/.aws:ro

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restjson
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    
  cache:
    image: redis:7
    restart: unless-stopped
    ports:
      - 6379:6379
    
