// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: json.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createNewJson = `-- name: CreateNewJson :one
INSERT INTO json_files (id, user_id, file_name, url)
VALUES($1, $2, $3, $4)
RETURNING id, created_at, updated_at, user_id, file_name, url
`

type CreateNewJsonParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	FileName string
	Url      string
}

func (q *Queries) CreateNewJson(ctx context.Context, arg CreateNewJsonParams) (JsonFile, error) {
	row := q.db.QueryRowContext(ctx, createNewJson,
		arg.ID,
		arg.UserID,
		arg.FileName,
		arg.Url,
	)
	var i JsonFile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FileName,
		&i.Url,
	)
	return i, err
}

const getJsonFile = `-- name: GetJsonFile :one
SELECT id, created_at, updated_at, user_id, file_name, url
FROM json_files
WHERE id=$1
`

func (q *Queries) GetJsonFile(ctx context.Context, id uuid.UUID) (JsonFile, error) {
	row := q.db.QueryRowContext(ctx, getJsonFile, id)
	var i JsonFile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FileName,
		&i.Url,
	)
	return i, err
}
