// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
	KeyHash    string
	LastUsedAt time.Time
}

type JsonFile struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FileName  string
	Url       string
}

type User struct {
	ID         uuid.UUID
	ProviderID string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      string
	Name       string
}

type UserSession struct {
	ID        string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
}
