FROM golang:1.24-bookworm AS builder
WORKDIR /app
COPY . .
RUN ./scripts/buildprod.sh

FROM debian:stable-slim AS runner
COPY --from=builder /app/webjson-web-api /usr/bin/webjson-web-api
CMD ["webjson-web-api"]
