FROM golang:1.24-bookworm AS builder
WORKDIR /app
COPY . .
RUN ./scripts/buildprod.sh

FROM debian:stable-slim AS runner
COPY --from=builder /app/webjson-public-api /usr/bin/webjson-public-api
CMD ["webjson-public-api"]
