FROM golang:1.24-bookworm AS builder
WORKDIR /app
COPY . .
RUN ./scripts/buildprod.sh

FROM golang:1.24-bookworm AS runner
COPY --from=builder /app/webjson-public-api /usr/bin/webjson-public-api
COPY --from=builder /app/sql/schema /app/sql/schema
RUN go install github.com/pressly/goose/v3/cmd/goose@latest
CMD ["webjson-public-api"]
