name: cd

on:
  push:
    branches: [main]

jobs:
  build_client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webjson-client:${{ github.sha }}

  build_server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webjson-server:${{ github.sha }}

  deploy:
    name: Deploy
    needs: [build_client, build_server]
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secret.DROPLET_SSH_KEY }}

      - name: SSH and pull
        run: |
          ssh -o StrictHostKeyChecking=no billy@{{ secrets.DROPLET_IP }} << 'EOF'
            cd /home/billy/webjson
            echo SHA=${{ github.sha }} > .env
            docker compose pull
            docker compose up -d
          EOF
