name: ci

on:
  pull_request:
    branches: [main]
  merge_group:
    

jobs:
  builds_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./frontend
        run: npm ci

      - name: Verifies that frontend can be built
        working-directory: ./frontend
        run: npm run build

  test_frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./frontend
        run: npm ci

      - name: Run tests
        working-directory: ./frontend
        run: npm run test

  lint_frontend:
    name: Lint frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./frontend
        run: npm ci

      - name: Lint
        working-directory: ./frontend
        run: npm run lint

  test_api:
    name: Test api
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"
      
      - name: Download dependencies
        working-directory: ./api
        run: go mod download

      - name: Run tests
        working-directory: ./api
        run: go test -cover ./...

      - name: Security check
        uses: securego/gosec@master
        with:
          args: "-exclude=G101 api/..."

  style_api:
    name: Style api
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Download dependencies
        working-directory: ./api
        run: go mod download

      - name: Style
        run: test -z $(go fmt ./...)
        working-directory: ./api

      - name: Lint
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          working-directory: ./api
