name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests_frontend_api:
    name: Tests frontend-api
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run tests
        run: go test -cover ./...
        working-directory: ./frontend-api

      - name: Security check
        run: gosec ./...
        working-directory: ./frontend-api


  style_frontend_api:
    name: Style frontend-api
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Style
        run: test -z $(go fmt ./...)
        working-directory: ./frontend-api

      - name: Lint
        run: staticcheck ./...
        working-directory: ./frontend-api
